language: ruby
rvm:
 - 2.6.3

before_install:
  - nvm install 12.5.0
  - >-
    openssl aes-256-cbc 
    -K $encrypted_7471ea73a54f_key 
    -iv $encrypted_7471ea73a54f_iv 
    -in github_deploy_key.enc 
    -out github_deploy_key 
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
install:
  - bundle install
  - npm install
script:
  - npm run build
  - ./deploy.sh